Array

In [3]:
import numpy as np

x = [1,2,3,4] 

y = np.array(x) # even if we put the whole array instead of storing it into a variable it still works

print(y)
#gives the dimension of the array
print(y.ndim)

[1 2 3 4]
1


In [4]:
l = []

for i in range(1,5):
    int_1 = input("Enter: ")
    l.append(int_1)

print(np.array(l))

Enter:  12
Enter:  13
Enter:  14
Enter:  15


['12' '13' '14' '15']


In [7]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [8]:
arr = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [9]:
# n dimension array
arr = np.array([1,2,3,4], ndmin = 10)
print (arr)
print (arr.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [28]:
# to fill array elements with zero
ar_zero = np.zeros(4)

print(ar_zero)

# to create one or two dimensional array with zeros
arr = np.zeros((3,4))

print(arr)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# to fill array elements with ones

arr_one = np.ones(4)
print (arr_one)
# two dimensional array of ones
arr = np.ones((3,4))
print (arr)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#empty array

arr = np.empty(4)
print(arr)

[1. 1. 1. 1.]


In [15]:
#Range
arr = np.arange(4)
print (arr)

[0 1 2 3]


In [16]:
#Identity array

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
arr = np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [12]:
# how to print an array with space interval
#linspace(start,stop,num,endpoint=true,retstep=false,dtype=none,axis=0)
arr = np.linspace(6,10,num=5,endpoint=True,retstep=False,dtype=None,axis=0)
print(arr)

[ 6.  7.  8.  9. 10.]


Numpy with Random numbers

In [37]:
#Rand() returns random values between zero and 1

var = np.random.rand(4)
print (var)

[0.28907189 0.74423051 0.73752164 0.79517577]


In [31]:
#2 dimensional random array
var = np.random.rand(2,5)
print(var)

[[0.3331108  0.41419643 0.75762801 0.24594282 0.75662548]
 [0.04003186 0.91986687 0.97581105 0.6806743  0.39117386]]


In [32]:
#Randn Function (this may return positive or negative values between zero and 1)

var = np.random.randn(5)
print(var)

[-0.54297553 -0.53347812  0.78052881 -0.59144652  0.04478204]


In [36]:
#randf (returs array of specified shape and fills with random floats values between zero and 1)

var = np.random.ranf(4)
print(var)

[0.64129747 0.3819527  0.03695045 0.16769215]


In [35]:
#randint (gives random values in given range)
#np.random.randint(min,max,totalValus)

var = np.random.randint(5,20,5)
print(var)

[ 5 13 10 17 10]


DataType

In [39]:
# gives data type of the given array

var = np.array([1,2,3,4])
print("Data Type: ", var.dtype)

Data Type:  int32


In [41]:
# convert one data type to another

var = np.array([1,2,3,4], dtype = np.int8) # this will change the data type to the initialize data type
print("Data Type: ",var.dtype)

Data Type:  int8


In [42]:
# convert one data type to another

var = np.array([1,2,3,4], dtype = "f") 
print("Data Type: ",var.dtype)
print (var)

Data Type:  float32
[1. 2. 3. 4.]


In [44]:
var = np.array([1,2,3,4]) 

vaarr = np.float32(var)

print("Data Type: ",var.dtype)
print("Data Type: ",vaarr.dtype)
print (var)
print (vaarr)

Data Type:  int32
Data Type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [45]:
# converting one data type to other and then converting new data type to the previous one

var = np.array([1,2,3,4]) 

vaarr = np.float32(var)

vaaarrr = np.int_(vaarr)

print("Data Type: ",var.dtype)
print("Data Type: ",vaarr.dtype)
print("Data Type: ",vaaarrr.dtype)
print (var)
print (vaarr)
print (vaaarrr)

Data Type:  int32
Data Type:  float32
Data Type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [47]:
var = np.array([1,2,3,4])
vaarr= var.astype(float)
print (var)
print (vaarr)

[1 2 3 4]
[1. 2. 3. 4.]


Arithmetic operations in numpy array

In [55]:
#addition
var = np.array([1,2,3,4])
varr = var + 3
print(varr)

[4 5 6 7]


In [49]:

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varr = var1 + var2
print(varr)

[2 4 6 8]


In [56]:
#subtraction
var = np.array([1,2,3,4])
varr = var - 3
print(varr)

[-2 -1  0  1]


In [57]:
#multiplication
var = np.array([1,2,3,4])
varr = var * 3
print(varr)

[ 3  6  9 12]


In [58]:
#divide
var = np.array([1,2,3,4])
varr = var / 3
print(varr)

[0.33333333 0.66666667 1.         1.33333333]


In [62]:
#modulus
var = np.array([1,2,3,4])
varr = var % 3
print(varr)

#reciprocal

var = np.array([1,2,3,4])
varr = np.reciprocal(var)
print(varr)

[1 2 0 1]
[1 0 0 0]


Arithmetic operations for 2D array

In [60]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varr = var1 + var2
print(varr)

[[2 4 6 8]
 [2 4 6 8]]


Arithmeric Functions

In [16]:
var = np.array ([1,2,3,4,5])

print ("min : ", np.min(var), np.argmin(var))
print ("min : ", np.max(var), np.argmax(var))
print ("sqrt : ", np.sqrt(var))

min :  1 0
min :  5 4
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798]


In [14]:
var = np.array([[2,1,3],[8,5,6]])

#axis 0 for column , 1 for row, extraxt the min or max along column or row
print(np.min(var,axis=0))

[2 1 3]


In [17]:
var = np.array([6,4,7,8])

print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

[-0.2794155  -0.7568025   0.6569866   0.98935825]
[ 0.96017029 -0.65364362  0.75390225 -0.14550003]
[ 6 10 17 25]


Numpy Array Shape and reshape

In [18]:
var = np.array([[1,2],[1,2]])

print(var)
print(var.shape)

[[1 2]
 [1 2]]
(2, 2)


In [20]:
#multidimensional Array

var = np.array([2,3,5,8], ndmin=4)

print(var)
print(var.ndim)
print(var.shape)

[[[[2 3 5 8]]]]
4
(1, 1, 1, 4)


In [25]:
#to convert one dim array in multidimensional array and to convert multidimensional array to one dim
#reshape function

var = np.array([1,2,3,4,5,6,9,6,4])
print(var)
print(var.ndim)

x = var.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6 9 6 4]
1
[[1 2 3]
 [4 5 6]
 [9 6 4]]
2


In [39]:
#converting one dimensional array into 3 dimensional
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print(var.ndim)

x = var.reshape(1,3,4)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [42]:
#3 or two dimensional to one dim

var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
print(var.ndim)

x = var.reshape(1,3,4)
print(x)
print(x.ndim)

one=x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


Broadcasting in numpy

In [49]:
var1 = np.array([4,6,3])
print(var1.shape)
print(var1)

var2 = np.array([[9],[5],[7]])
print(var2.shape)
print(var2)

print(var1+var2)

(3,)
[4 6 3]
(3, 1)
[[9]
 [5]
 [7]]
[[13 15 12]
 [ 9 11  8]
 [11 13 10]]


In [52]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[2,8,9]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[ 2  3  4]
 [ 4 10 11]]


INDEXING

In [55]:
#one dimensional
var = np.array([9,8,7,6])
#               0,1,2,3
#              -4,-3,-2.-1
print(var[1])
print(var[-4])

8
9


In [58]:
#two dimensional
var = np.array([[9,5,6,3],[7,3,4,8]])

print(var[1,2])

4


In [65]:
#three dimensional

var = np.array([[[9,5,6,3],[8,3,5,7],[7,3,4,8]]])

print(var[0,1,1])

3


Slicing

In [71]:
#to get the particular dataset

var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6
print(var)

print("2 to 5: ", var[1:5])
print("2 to end: ", var[1:])
print("start to 5 :", var[:5])
print("stop :", var[::2]) #start to end point but by jumping
print("stop :", var[1:5:2]) #start to end point but by jumping

[1 2 3 4 5 6 7]
2 to 5:  [2 3 4 5]
2 to end:  [2 3 4 5 6 7]
start to 5 : [1 2 3 4 5]
stop : [1 3 5 7]
stop : [2 4]


In [74]:
#2 dimentional
var = np.array([[9,5,6,3,8],[8,3,5,7,2],[7,3,4,8,6]])

print("8 : ", var[2,1:])

8 :  [3 4 8 6]


In [81]:
#3 dimensional

var = np.array([[[9,5,6,3],[8,3,5,7],[7,3,4,8]]])

print(var[0,1,1:])

[3 5 7]
